### PR TITLE
Add vmlinux.h generated from Linux kernel BTF data

### PR DESCRIPTION
**Pull request by ThisSeanZhang**
Generated vmlinux.h using bpftool on Linux kernel version "6.6.54-2-MANJARO".

for [#980](https://github.com/libbpf/libbpf-rs/pull/980)

### CODE REVIEW

**Comment by ThisSeanZhang** [comment]
Should I create a new branch?

**Comment by danielocfb** [comment]
Thanks for the pull request @ThisSeanZhang . I think we want to try and converge on using a single kernel configuration as well as version here and then bulk update all headers (existing ones can stay for the time being), otherwise this will get very messy very quickly.

I believe retsnoop has somewhat of a usable generation infra in https://github.com/anakryiko/retsnoop/blob/master/scripts/gen-vmlinux-headers.sh (I think it covers all arches we care about except for loongarch64; I am not familiar with it and we'll have to see what to do about that, but for the time being I am fine with leaving this as a one-off straddler). My recommendation is to use that script to generate headers for 6.6 and then we can include them. I can look into that, but it's unlikely to happen this week. So feel free to give it a shot if you have time.

**Comment by danielocfb** [comment]
Just for reference, for loongarch we may want to pull the cross compile toolchain from https://github.com/loongson/build-tools/

**Comment by ThisSeanZhang** [comment]
I tried cloning and compiling the target but encountered the following error on Debian:
in Debian: 
```text
  BPF      .output/calib_feat.bpf.o
calib_feat.bpf.c:86:74: error: no member named 'cookie' in 'struct bpf_attr::(unnamed at x86/vmlinux.h:9567:2)'
        has_rawtp_cookie = bpf_core_field_exists(union bpf_attr, raw_tracepoint.cookie);
                           ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^~~~~~~
.output/include/bpf/bpf_core_read.h:188:49: note: expanded from macro 'bpf_core_field_exists'
        __builtin_preserve_field_info(___bpf_field_ref(field), BPF_FIELD_EXISTS)
                                      ~~~~~~~~~~~~~~~~~^~~~~~
.output/include/bpf/bpf_core_read.h:173:52: note: expanded from macro '___bpf_field_ref'
        ___bpf_apply(___bpf_field_ref, ___bpf_narg(args))(args)
        ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^~~~~
.output/include/bpf/bpf_core_read.h:167:62: note: expanded from macro '___bpf_field_ref2'
#define ___bpf_field_ref2(type, field)  (___bpf_typeof(type)->field)
                                         ~~~~~~~~~~~~~~~~~~~~~^~~~~
1 error generated.
make: *** [Makefile:119: .output/calib_feat.bpf.o] Error 1
make: *** Waiting for unfinished jobs....
...                        libbfd: [ OFF ]
...               clang-bpf-co-re: [ on  ]
...                          llvm: [ on  ]
...                        libcap: [ OFF ]
  MKDIR    /root/retsnoop/src/.output/bpftool/bootstrap/
  MKDIR    /root/retsnoop/src/.output/bpftool/bootstrap/libbpf/include/bpf
  MKDIR    /root/retsnoop/src/.output/bpftool/bootstrap/libbpf/
  INSTALL  /root/retsnoop/src/.output/bpftool/bootstrap/libbpf/include/bpf/relo_core.h
  INSTALL  /root/retsnoop/src/.output/bpftool/bootstrap/libbpf/include/bpf/hashmap.h
  INSTALL  /root/retsnoop/src/.output/bpftool/bootstrap/libbpf/include/bpf/libbpf_internal.h
  MKDIR    /root/retsnoop/src/.output/bpftool/bootstrap/libbpf/staticobjs
  INSTALL  bpf.h libbpf.h btf.h libbpf_common.h libbpf_legacy.h bpf_helpers.h bpf_helper_defs.h bpf_tracing.h bpf_endian.h bpf_core_read.h skel_internal.h libbpf_version.h usdt.bpf.h
  CC       /root/retsnoop/src/.output/bpftool/bootstrap/libbpf/staticobjs/bpf.o
```
On ArchLinux, everything is the same except `libcap: [on]`.

I’m unsure how to proceed. Could you offer guidance?

This issue might be beyond my current skill level 😢.

**Comment by anakryiko** [comment]
@ThisSeanZhang you don't need to build or run retsnoop itself, just look at https://github.com/anakryiko/retsnoop/blob/master/scripts/gen-vmlinux-headers.sh and use that as a base

**Comment by ThisSeanZhang** [comment]
I tried following the next step in the script and manually executed `bpftool btf dump file ./vmlinux format c > ./vmlinux.h` in the generated directory `<path>/retsnoop/scripts/.linux_builds/x86_64/`, then checked the generated *vmlinux.h*. 

It includes the *cookie* member variable within the structures. 

file snippet is as follows: 
```c
union bpf_attr {
	struct {
		__u32 map_type;
		__u32 key_size;
		__u32 value_size;
		__u32 max_entries;
		__u32 map_flags;
		__u32 inner_map_fd;
		__u32 numa_node;
		char map_name[16];
		__u32 map_ifindex;
		__u32 btf_fd;
		__u32 btf_key_type_id;
		__u32 btf_value_type_id;
		__u32 btf_vmlinux_value_type_id;
		__u64 map_extra;
	};
	struct {
		__u32 map_fd;
		__u64 key;
		union {
			__u64 value;
			__u64 next_key;
		};
		__u64 flags;
	};
	struct {
		__u64 in_batch;
		__u64 out_batch;
		__u64 keys;
		__u64 values;
		__u32 count;
		__u32 map_fd;
		__u64 elem_flags;
		__u64 flags;
	} batch;
	struct {
		__u32 prog_type;
		__u32 insn_cnt;
		__u64 insns;
		__u64 license;
		__u32 log_level;
		__u32 log_size;
		__u64 log_buf;
		__u32 kern_version;
		__u32 prog_flags;
		char prog_name[16];
		__u32 prog_ifindex;
		__u32 expected_attach_type;
		__u32 prog_btf_fd;
		__u32 func_info_rec_size;
		__u64 func_info;
		__u32 func_info_cnt;
		__u32 line_info_rec_size;
		__u64 line_info;
		__u32 line_info_cnt;
		__u32 attach_btf_id;
		union {
			__u32 attach_prog_fd;
			__u32 attach_btf_obj_fd;
		};
		__u32 core_relo_cnt;
		__u64 fd_array;
		__u64 core_relos;
		__u32 core_relo_rec_size;
		__u32 log_true_size;
	};
	struct {
		__u64 pathname;
		__u32 bpf_fd;
		__u32 file_flags;
		__s32 path_fd;
	};
	struct {
		union {
			__u32 target_fd;
			__u32 target_ifindex;
		};
		__u32 attach_bpf_fd;
		__u32 attach_type;
		__u32 attach_flags;
		__u32 replace_bpf_fd;
		union {
			__u32 relative_fd;
			__u32 relative_id;
		};
		__u64 expected_revision;
	};
	struct {
		__u32 prog_fd;
		__u32 retval;
		__u32 data_size_in;
		__u32 data_size_out;
		__u64 data_in;
		__u64 data_out;
		__u32 repeat;
		__u32 duration;
		__u32 ctx_size_in;
		__u32 ctx_size_out;
		__u64 ctx_in;
		__u64 ctx_out;
		__u32 flags;
		__u32 cpu;
		__u32 batch_size;
	} test;
	struct {
		union {
			__u32 start_id;
			__u32 prog_id;
			__u32 map_id;
			__u32 btf_id;
			__u32 link_id;
		};
		__u32 next_id;
		__u32 open_flags;
	};
	struct {
		__u32 bpf_fd;
		__u32 info_len;
		__u64 info;
	} info;
	struct {
		union {
			__u32 target_fd;
			__u32 target_ifindex;
		};
		__u32 attach_type;
		__u32 query_flags;
		__u32 attach_flags;
		__u64 prog_ids;
		union {
			__u32 prog_cnt;
			__u32 count;
		};
		__u64 prog_attach_flags;
		__u64 link_ids;
		__u64 link_attach_flags;
		__u64 revision;
	} query;
	struct {
		__u64 name;
		__u32 prog_fd;
	} raw_tracepoint;
	struct {
		__u64 btf;
		__u64 btf_log_buf;
		__u32 btf_size;
		__u32 btf_log_size;
		__u32 btf_log_level;
		__u32 btf_log_true_size;
	};
	struct {
		__u32 pid;
		__u32 fd;
		__u32 flags;
		__u32 buf_len;
		__u64 buf;
		__u32 prog_id;
		__u32 fd_type;
		__u64 probe_offset;
		__u64 probe_addr;
	} task_fd_query;
	struct {
		union {
			__u32 prog_fd;
			__u32 map_fd;
		};
		union {
			__u32 target_fd;
			__u32 target_ifindex;
		};
		__u32 attach_type;
		__u32 flags;
		union {
			__u32 target_btf_id;
			struct {
				__u64 iter_info;
				__u32 iter_info_len;
			};
			struct {
				__u64 bpf_cookie;
			} perf_event;
			struct {
				__u32 flags;
				__u32 cnt;
				__u64 syms;
				__u64 addrs;
				__u64 cookies;
			} kprobe_multi;
			struct {
				__u32 target_btf_id;
				__u64 cookie;
			} tracing;
			struct {
				__u32 pf;
				__u32 hooknum;
				__s32 priority;
				__u32 flags;
			} netfilter;
			struct {
				union {
					__u32 relative_fd;
					__u32 relative_id;
				};
				__u64 expected_revision;
			} tcx;
			struct {
				__u64 path;
				__u64 offsets;
				__u64 ref_ctr_offsets;
				__u64 cookies;
				__u32 cnt;
				__u32 flags;
				__u32 pid;
			} uprobe_multi;
		};
	} link_create;
	struct {
		__u32 link_fd;
		union {
			__u32 new_prog_fd;
			__u32 new_map_fd;
		};
		__u32 flags;
		union {
			__u32 old_prog_fd;
			__u32 old_map_fd;
		};
	} link_update;
	struct {
		__u32 link_fd;
	} link_detach;
	struct {
		__u32 type;
	} enable_stats;
	struct {
		__u32 link_fd;
		__u32 flags;
	} iter_create;
	struct {
		__u32 prog_fd;
		__u32 map_fd;
		__u32 flags;
	} prog_bind_map;
};
```

The complete file is as follows:

[vmlinux.h.zip](https://github.com/user-attachments/files/17595282/vmlinux.h.zip)

**Comment by danielocfb** [comment]
Will be taken care off by https://github.com/libbpf/vmlinux.h/pull/4.

**Pull request closed without merging**
